### ISSUE TITLE
Multiple Class

### ISSUE THREAD

**Issue by surumud** [jaschaephraim/jquery-shift-heading-levels#2] opened 2016-06-09 20:22 UTC
Hi
any ideas  how can I implement this shift heading levels into multiple class like below

```
<h2 class="title>text1</h2>
<h2 class="title>text2</h2>
<h2 class="title>text3</h2>
<h2 class="title>text4</h2>
```

seems it worked only on the first class

**Comment by jaschaephraim** [comment] 2016-06-21 19:14
Hello surumud,

Your example should definitely work as intended, just be sure you're closing the quotes on your class names:

``` html
<h2 class="title">text1</h2>
```

not:

``` html
<h2 class="title>text1</h2>
```

**Closed as completed by jaschaephraim** 2016-06-21 19:14 UTC
